# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormaddCoffee(object):
    def setupUi(self, FormaddCoffee):
        FormaddCoffee.setObjectName("FormaddCoffee")
        FormaddCoffee.resize(580, 216)
        FormaddCoffee.setMinimumSize(QtCore.QSize(580, 170))
        self.label_6 = QtWidgets.QLabel(FormaddCoffee)
        self.label_6.setGeometry(QtCore.QRect(-51, 49, 55, 20))
        self.label_6.setObjectName("label_6")
        self.CBRoast = QtWidgets.QComboBox(FormaddCoffee)
        self.CBRoast.setGeometry(QtCore.QRect(139, 58, 250, 20))
        self.CBRoast.setObjectName("CBRoast")
        self.BtnCancel = QtWidgets.QPushButton(FormaddCoffee)
        self.BtnCancel.setGeometry(QtCore.QRect(290, 180, 81, 23))
        self.BtnCancel.setObjectName("BtnCancel")
        self.label_9 = QtWidgets.QLabel(FormaddCoffee)
        self.label_9.setGeometry(QtCore.QRect(11, 5, 48, 20))
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(FormaddCoffee)
        self.label_5.setGeometry(QtCore.QRect(10, 57, 55, 20))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(FormaddCoffee)
        self.label_8.setGeometry(QtCore.QRect(10, 109, 33, 20))
        self.label_8.setObjectName("label_8")
        self.CBForm = QtWidgets.QComboBox(FormaddCoffee)
        self.CBForm.setGeometry(QtCore.QRect(139, 33, 251, 20))
        self.CBForm.setObjectName("CBForm")
        self.label_7 = QtWidgets.QLabel(FormaddCoffee)
        self.label_7.setGeometry(QtCore.QRect(10, 83, 26, 20))
        self.label_7.setObjectName("label_7")
        self.BtnOK = QtWidgets.QPushButton(FormaddCoffee)
        self.BtnOK.setGeometry(QtCore.QRect(110, 180, 75, 23))
        self.BtnOK.setObjectName("BtnOK")
        self.label_2 = QtWidgets.QLabel(FormaddCoffee)
        self.label_2.setGeometry(QtCore.QRect(10, 31, 120, 20))
        self.label_2.setObjectName("label_2")
        self.editPrice = QtWidgets.QLineEdit(FormaddCoffee)
        self.editPrice.setGeometry(QtCore.QRect(139, 81, 250, 22))
        self.editPrice.setObjectName("editPrice")
        self.editValue = QtWidgets.QLineEdit(FormaddCoffee)
        self.editValue.setGeometry(QtCore.QRect(139, 107, 250, 22))
        self.editValue.setObjectName("editValue")
        self.editName = QtWidgets.QLineEdit(FormaddCoffee)
        self.editName.setGeometry(QtCore.QRect(139, 7, 251, 22))
        self.editName.setObjectName("editName")
        self.editDescr = QtWidgets.QLineEdit(FormaddCoffee)
        self.editDescr.setGeometry(QtCore.QRect(139, 137, 400, 22))
        self.editDescr.setObjectName("editDescr")
        self.label_10 = QtWidgets.QLabel(FormaddCoffee)
        self.label_10.setGeometry(QtCore.QRect(10, 137, 48, 20))
        self.label_10.setObjectName("label_10")
        self.label_6.raise_()
        self.CBRoast.raise_()
        self.BtnCancel.raise_()
        self.label_9.raise_()
        self.label_5.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.BtnOK.raise_()
        self.label_2.raise_()
        self.CBForm.raise_()
        self.editPrice.raise_()
        self.editValue.raise_()
        self.editName.raise_()
        self.editDescr.raise_()
        self.label_10.raise_()

        self.retranslateUi(FormaddCoffee)
        QtCore.QMetaObject.connectSlotsByName(FormaddCoffee)

    def retranslateUi(self, FormaddCoffee):
        _translate = QtCore.QCoreApplication.translate
        FormaddCoffee.setWindowTitle(_translate("FormaddCoffee", "Сорт кофе - добавление строки"))
        self.label_6.setText(_translate("FormaddCoffee", "Обжарка   "))
        self.BtnCancel.setText(_translate("FormaddCoffee", "Cancel"))
        self.label_9.setText(_translate("FormaddCoffee", "Название"))
        self.label_5.setText(_translate("FormaddCoffee", "Обжарка   "))
        self.label_8.setText(_translate("FormaddCoffee", "Объем"))
        self.label_7.setText(_translate("FormaddCoffee", "Цена"))
        self.BtnOK.setText(_translate("FormaddCoffee", "OK"))
        self.label_2.setText(_translate("FormaddCoffee", "Форма (в зернах и т.д.)"))
        self.label_10.setText(_translate("FormaddCoffee", "Описание"))
