# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmMain(object):
    def setupUi(self, FrmMain):
        FrmMain.setObjectName("FrmMain")
        FrmMain.resize(735, 350)
        FrmMain.setMinimumSize(QtCore.QSize(421, 229))
        self.verticalLayoutWidget = QtWidgets.QWidget(FrmMain)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 711, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HLayout = QtWidgets.QHBoxLayout()
        self.HLayout.setObjectName("HLayout")
        self.verticalLayout.addLayout(self.HLayout)
        self.labelRes = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelRes.setObjectName("labelRes")
        self.verticalLayout.addWidget(self.labelRes)
        self.tableWidgetRes = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidgetRes.setObjectName("tableWidgetRes")
        self.tableWidgetRes.setColumnCount(0)
        self.tableWidgetRes.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidgetRes)
        self.BtnADDForm = QtWidgets.QPushButton(FrmMain)
        self.BtnADDForm.setGeometry(QtCore.QRect(10, 0, 111, 21))
        self.BtnADDForm.setObjectName("BtnADDForm")
        self.BtnADDRoast = QtWidgets.QPushButton(FrmMain)
        self.BtnADDRoast.setGeometry(QtCore.QRect(120, 0, 111, 21))
        self.BtnADDRoast.setObjectName("BtnADDRoast")
        self.BtnADDCoffee = QtWidgets.QPushButton(FrmMain)
        self.BtnADDCoffee.setGeometry(QtCore.QRect(230, 0, 111, 21))
        self.BtnADDCoffee.setObjectName("BtnADDCoffee")

        self.retranslateUi(FrmMain)
        QtCore.QMetaObject.connectSlotsByName(FrmMain)

    def retranslateUi(self, FrmMain):
        _translate = QtCore.QCoreApplication.translate
        FrmMain.setWindowTitle(_translate("FrmMain", "Form"))
        self.labelRes.setText(_translate("FrmMain", "TextLabel"))
        self.BtnADDForm.setText(_translate("FrmMain", "Добавить форму"))
        self.BtnADDRoast.setText(_translate("FrmMain", "Добавить обжарку"))
        self.BtnADDCoffee.setText(_translate("FrmMain", "Добавить вкус"))
